### PR TITLE
Add calls puzzler

### PR DESCRIPTION
**Pull request by TWiStErRob**

### CODE REVIEW

**Comment by LouisCAD** [comment]
You can make it more puzzling by adding a call before `fun` declaration, and a call before `val` declaration.

**Comment by TWiStErRob** [comment]
@LouisCAD it would be a long multiple-choice question then... 3^3+1 options

That being said, anyone who has write access to this repo (or PR) feel free to adjust it.

**Comment by TWiStErRob** [comment]
@LouisCAD / @angryziber is there anything I need to do here?

**Comment by angryziber** [comment]
I think the puzzler is great as it is, thanks!
Thanks also to @LouisCAD for an important observation

**Pull request merged**
