### PR TITLE
Dollar in multiline literals

### PR DESCRIPTION
**Pull request by voddan**
This one may be a bit too long, but the workaround is bizarre!

### CODE REVIEW

**Comment by voddan** [comment]
Actually I have been thinking if we can improve this puzzler by asking "What literal should we use to produce the desired effect?"

**Comment by angryziber** [comment]
There is a puzzler on the same topic already:
https://github.com/angryziber/kotlin-puzzlers/blob/master/src/syntax/strings/MultilineLiteral.kts

Maybe we don't need two

**Comment by voddan** [comment]
I want something that would mention the `${'$'}` construct.

**Comment by voddan** [comment]
Second attempt: https://github.com/angryziber/kotlin-puzzlers/pull/19/commits

**Pull request merged**
